[error] java.io.IOException: Could not create directory G:\Mi unidad\TrainingSura\Cursos\Scala\FacturaExcercise\target\streams\_global\dependencyPositions\_global\streams: java.nio.file.FileAlreadyExistsException: G:\Mi unidad\TrainingSura\Cursos\Scala\FacturaExcercise\target\streams
[error] 	at sbt.io.IO$.createDirectory(IO.scala:337)
[error] 	at sbt.std.Streams$$anon$2$$anon$3.cacheDirectory$lzycompute(Streams.scala:192)
[error] 	at sbt.std.Streams$$anon$2$$anon$3.cacheDirectory(Streams.scala:190)
[error] 	at sbt.std.Streams$$anon$2$$anon$3.cacheStoreFactory$lzycompute(Streams.scala:196)
[error] 	at sbt.std.Streams$$anon$2$$anon$3.cacheStoreFactory(Streams.scala:196)
[error] 	at sbt.Classpaths$.$anonfun$dependencyPositionsTask$1(Defaults.scala:3699)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:68)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error] 	at sbt.Execute.work(Execute.scala:291)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[error] 	at java.base/java.lang.Thread.run(Thread.java:829)
[error] Caused by: java.nio.file.FileAlreadyExistsException: G:\Mi unidad\TrainingSura\Cursos\Scala\FacturaExcercise\target\streams
[error] 	at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:87)
[error] 	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
[error] 	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
[error] 	at java.base/sun.nio.fs.WindowsFileSystemProvider.createDirectory(WindowsFileSystemProvider.java:509)
[error] 	at java.base/java.nio.file.Files.createDirectory(Files.java:690)
[error] 	at java.base/java.nio.file.Files.createAndCheckIsDirectory(Files.java:797)
[error] 	at java.base/java.nio.file.Files.createDirectories(Files.java:783)
[error] 	at sbt.io.IO$.$anonfun$createDirectory$1(IO.scala:333)
[error] 	at sbt.internal.io.Retry$.apply(Retry.scala:46)
[error] 	at sbt.internal.io.Retry$.apply(Retry.scala:28)
[error] 	at sbt.internal.io.Retry$.apply(Retry.scala:23)
[error] 	at sbt.io.IO$.createDirectory(IO.scala:335)
[error] 	at sbt.std.Streams$$anon$2$$anon$3.cacheDirectory$lzycompute(Streams.scala:192)
[error] 	at sbt.std.Streams$$anon$2$$anon$3.cacheDirectory(Streams.scala:190)
[error] 	at sbt.std.Streams$$anon$2$$anon$3.cacheStoreFactory$lzycompute(Streams.scala:196)
[error] 	at sbt.std.Streams$$anon$2$$anon$3.cacheStoreFactory(Streams.scala:196)
[error] 	at sbt.Classpaths$.$anonfun$dependencyPositionsTask$1(Defaults.scala:3699)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:68)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error] 	at sbt.Execute.work(Execute.scala:291)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[error] 	at java.base/java.lang.Thread.run(Thread.java:829)
[error] (dependencyPositions) java.io.IOException: Could not create directory G:\Mi unidad\TrainingSura\Cursos\Scala\FacturaExcercise\target\streams\_global\dependencyPositions\_global\streams: java.nio.file.FileAlreadyExistsException: G:\Mi unidad\TrainingSura\Cursos\Scala\FacturaExcercise\target\streams
